DiamondLightSource/python-murfey

src/transferscript/server/main.py
FastAPI should run blocking I/O (such as SQLAlchemy queries) faster if it is not in an asynchronous method. This is because it will run non-asynchronous path operation functions in a thread which it then `await`s. See the bottom of https://fastapi.tiangolo.com/async/ and the "About `def` vs `async def`" section of https://fastapi.tiangolo.com/tutorial/sql-databases/
=> Use normal methods for blocking I/O

MANIFEST.in, pip_bootstrap.md, setup.cfg, src/murfey/bootstrap/__main__.py, src/murfey/server/main.py, src/murfey/templates/base.html, src/murfey/templates/bootstrap.html, src/murfey/templates/home.html
On the server:
* Modify endpoint `/pypi/package` to rewrite the response and change all URLs to point to an endpoint `/pypi/package/file` instead
* Add endpoint `/pypi/package/file` which then downloads and passes through a particular file download
* Add endpoint `/bootstrap` pointing to an instruction page on how to install the client via a non-public network. The user is instructed to download a murfey wheel file, then run `murfey.bootstrap` from _within the wheel_ (ie. this calls the file `src/murfey/bootstrap/__main__.py`, and is not a command/entry point `murfey.bootstrap`)
* Add endpoint `/bootstrap/pip.whl` which downloads one particular version of pip from pypi
* Add endpoint `/bootstrap/murfey.whl` which downloads the most recent version of a murfey wheel
* The latter two …
=> Introduce client bootstrapping mechanism

src/murfey/utils/rsync.py, tests/utils/test_rsync.py
This will be useful for tomography data sets which require a file name conversion before processing.
A function that takes the default file names and directory structure and returns modified versions can be passed to `RsyncPipe` for this purpose
=> Allow modification of `rsync` destination directory structure and file names

src/murfey/client/__init__.py, src/murfey/client/main.py, src/murfey/server/main.py, src/murfey/server/websocket.py
Add updating functionality to websockets.
Server broadcasts to all connected clients when a new client joins, and when a post request is received.
To see this you can start a server (murfey.server), client (murfey) and send a post request eg. 
`curl -X POST http://127.0.0.1:8000/visits/cm31111-1/files --data '{"name": "microscope", "description": "8361", "size": 25, "timestamp": 24.0}' -H "Content-Type: application/json"`
=> Add websockets support

src/murfey/client/__init__.py, src/murfey/server/__init__.py, src/murfey/server/ispyb.py, src/murfey/server/main.py, src/murfey/server/websocket.py, src/murfey/util/models.py
Note: as of this PR the server must be started with "murfey.server -e devrmq -t PikaTransport" rather than just "murfey.server" because the dev environment is no longer hardcoded.
Send messages via Zocalo to start a Data Collection.
Uses the visit given when the Murfey client is started and looks up session_id with SQLAlchemy.
Some fields in the DC entry are filled in.
=> Start Data Collection in ISPyB

requirements_dev.txt, src/murfey/server/__init__.py, src/murfey/server/config.py, src/murfey/server/main.py
This will allow microscope specific information such as calibrated pixel sizes to be stored in a location accessible to the server and looked up when required for processing parameters. Environment variable `MURFEY_MACHINE_CONFIGURATION` used to point to config file
=> Add basic setup to allow reading of machine configuration files

src/murfey/client/analyser.py, src/murfey/client/context.py, src/murfey/server/main.py, tests/client/test.py, tests/client/test_analyser.py, tests/client/test_context.py
Adds mechanisms for determining the acquisition software from the names of transferred files and then perform actions on every transfer. So far only actions for `Tomography 5` are implemented. This will allow processing to be performed based on which files have been transferred. This also contains the logic to determine when tilt series have been completed in both configurations where one tilt series is collected at once and where beam shift is used to collect multiple positions at each angle before collecting at the next angle. It should also cover the case where the files are transferred out of order, although less efficiently.
=> Determine acquisition software and perform tasks accordingly

requirements_dev.txt, src/murfey/client/__init__.py, src/murfey/client/analyser.py, src/murfey/client/context.py, src/murfey/client/instance_environment.py, src/murfey/client/tui/app.py, src/murfey/client/websocket.py, src/murfey/server/__init__.py, src/murfey/server/main.py, tests/client/test_context.py, tests/client/test_instance_environment.py
At various stages primary key IDs obtained on insert into ISPyB are needed to trigger processing. This should mostly handle this need by triggering callback functions that clear buffered API calls once the relevant ID becomes available. Will benefit from some cleanup in the future
=> Handle ISPyB ID requirements

src/murfey/client/__init__.py, src/murfey/client/tui/app.py, src/murfey/client/watchdir.py
- `--appearance_time` flag for client provides an amount of the past from which directories will be copied in hours
- if `--appearance_time` is not provided then `DirWatcher` will find the first top level directory (with respect to the base path) in which a new file appears and `rsync` that directory and any other more recently created directories
- `--real_dc` flag for client turns on data collection related API calls (i.e. ISPyB inserts and Zocalo processing triggers)
- default real data collections to false at the moment for debugging
=> Add ability to only rsync recent or active directories

src/murfey/client/tui/app.py, src/murfey/server/api.py
The destination path for a remote rsync operation must be relative to the rsync base path of the rsync daemon
=> Fix suggested destination path or remote rsync

src/murfey/client/__init__.py, src/murfey/client/analyser.py
This allows data collections to be started for older versions of Tomo where metadata files are only written per position rather than per movie
=> Quick fix to force metadata to be read from any mdoc file

src/murfey/client/analyser.py
Missed a case where unseen xmls are registered even when forcing mdoc reading
=> Reduce the number of metadata reads from mdoc files

src/murfey/client/__init__.py, src/murfey/client/context.py, src/murfey/client/contexts/tomo.py, src/murfey/client/instance_environment.py, src/murfey/server/config.py
Software versions can be specified in the machine configuration. This is only setup got parsing of files from TFS Tomography at the moment. Should resolve #103
=> Parse file names based on acquisition software version

src/murfey/client/tui/app.py, src/murfey/server/api.py
This will make the user experience easier by providing at least most of the gain reference path. This is DLS specific at the moment: `processing/gain.mrc` within the visit directory.
=> Add a default gain reference path

src/murfey/client/__init__.py
Changes the behaviour of a command line argument so that this is `True` by default for convenience
=> Read metadata from any mdoc file by default

src/murfey/client/tui/app.py
Use a partial to pass the visit path to `_start_rsyncer` callback to facilitate copying of gain reference file
=> Fix for gain reference copying

src/murfey/client/rsync.py, src/murfey/client/tui/app.py
Press "c" to be prompted about whether to remove files that have been copied. If yes this will run a final `rsync` on the files in source to the previously used destination to make sure that all copies are complete.
=> Add an option to remove files after rsync when closing client

src/murfey/client/context.py, tests/client/test_context.py
Currently TFS Tomo acquisition software only writes a position mdoc after the full tilt series has been collected so this can be used as a more reliable indicator of tilt series completion
=> Use mdocs to determine tilt series completion

src/murfey/client/context.py, src/murfey/client/instance_environment.py, src/murfey/client/tui/app.py, src/murfey/server/api.py, src/murfey/util/models.py
and pass pixel size to tomo align service.
This means the tilt offset will be taken into account by the tomo_align service, and the pixel size will be scaled and stored in the database as pixel_spacing.
This should fix https://github.com/DiamondLightSource/python-murfey/issues/129
=> Use manual tilt offset from input parameters 

src/murfey/client/analyser.py, src/murfey/client/context.py, src/murfey/server/config.py
If the detector is capable of collecting in superresolution then `superres` should be set to `True` in the machine configuration. If the data are then unbinned (as determined from mdoc files) the data has been collected in superresolution. 
Allow calibrated pixel sizes based on magnification to be used rather than the pixel size direct from the mdoc.
=> Automatically detect superres data collections and use calibrated pixel sizes

src/murfey/server/api.py
for the message sent to alignment.
I think the other movie_id references are okay to remain.
=> Add path_pattern and remove movie_id fields 

src/murfey/client/context.py, src/murfey/server/config.py
Currently only supports configuring for Tomography5 acquisition software
Resolves #138
=> Allow substrings required in data file names to be configured 

catalog-info.yaml
Hi Dan,
Cheers for adding an entity descriptor for the developer portal! I thought it might be nice to split the entity into a client & server component to reflect the real application. I've edited the `catalog-info.yaml` file with what I think is right, but I'm not 100% sure I've captured things correctly, any chance you could answer the following?
- Is Murfey is an entire system unto itself? If so it would be good to add a `system` component representing it, if not it's probably best left out. 
- Is the client is a library or something else? It reads as if it has a web interface which I guess would make it a website under the [common component types](https://diamondlightsource.github.io/developer-portal/user/references/common-component-types/) - though if you have some other way of …
=> Separate client & server in dev-portal

src/murfey/client/tui/screens.py
Do not allow selection of subdirectories of already selected directories to avoid multiple copies being made
=> Be more restrictive with directory selection

src/murfey/client/tui/app.py, src/murfey/server/api.py, src/murfey/server/demo_api.py
Increment the transferred file count and volume on transfer of every individual file in Prometheus. This wasn't done before because of concerns over large numbers of rapid connections to the Murfey database. We are keeping the transfer registration in the Murfey database batched but hopefully Prometheus can handle the throughput better. Closes #193
=> Make transfer monitoring through Prometheus more accurate

src/murfey/server/api.py
In EER fractionation file the dose should be per EER frame not per fraction. Resolves #226
=> EER dose fix

src/murfey/client/contexts/tomo.py
We hit an issue where the gain reference in the processing form is ignored for tomography. This will hopefully resolve that
=> Use user-supplied tomography gain if available

src/murfey/client/contexts/tomo.py, src/murfey/server/__init__.py, src/murfey/server/api.py, src/murfey/server/demo_api.py, src/murfey/util/db.py, src/murfey/util/models.py
This implements a check that processing has not already been requested, and also checks the length of the tilt list after motion correction.
Closes #257
=> Change the tomography alignment request methods to avoid cases of duplication

.azure-pipelines/azure-pipelines.yml, .azure-pipelines/ci.yml, pyproject.toml
Resolves issue #272 and #256.
Changes:
- Moved `[clem]` dependencies under `[server]` in `pyproject.toml`, now that their use case is more clear.
- Removed `mysql-connector-python` as an explicit dependency; it will be controlled by `ispyb`.
- Updated `ispyb-database` and `mariadb` versions used by Azure Pipelines to latest stable ones. These are now compatible with `ispyb v10.0.0`
`pip install` Verification for Python Versions:
=> Updated CI/CD environment

src/murfey/client/tui/screens.py, src/murfey/server/api.py, src/murfey/server/demo_api.py
Downloads tiffs individually, avoiding zip archiving. The zip archive method was too slow and didn't give enough feedback as the zip was being performed over a large directory as the first step
=> Improve tiff downloading

logfile, pyproject.toml, src/murfey/server/clem/api.py, src/murfey/workflows/lif_to_tiff.py
Adds an endpoint plugin for workflows with the intention of extending in the future. Requires LIF to TIFF conversion to be packaged into a command line application. Resolves #279
=> Send LIF to TIFF conversion to a cluster

src/murfey/client/contexts/tomo.py, src/murfey/server/__init__.py, src/murfey/server/api.py
Tomogram alignment sometimes isn't requested as the database doesn't have a tilt series length. This happens if an mdoc is seen before all the tilts. To solve this, always insert tilt series length into the database when an mdoc is seen.
=> Always update the tilt series length in the database after an mdoc

src/murfey/util/clem/lif.py, src/murfey/util/clem/tiff.py, src/murfey/workflows/lif_to_tiff.py
Further work on issues raised in #304.
=> More CLEM fixes

src/murfey/server/ispyb.py
On sends from a `TransportManager` instance there is currently a check on the connection. This doesn't work as it tries to start and existing thread. A new transport object should be created and connected instead. Resolves #324
=> When re-establishing RabbitMQ connection create new transport object

src/murfey/server/__init__.py
We aren't currently displaying the processing of tomography tilts on grafana. But we do create the prometheus metric objects needed for that, and they only require a program id.
As the program id is sent in the `motion_corrected` feedback message, I think we can just add an increment to the metric and it will work.
Do you see any reason why this wouldn't work?
=> Record tomography preprocessing in prometheus

src/murfey/client/contexts/tomo.py, tests/client/test_context.py
Currently we return "0" if no tilt series number can be found. This then leads to tilt series names of the form "name_0".
It would be better to return no tilt series number then put in logic to handle that case.
=> Try and handle the case where users enter their own tomogram names

.github/workflows/ci.yml, .github/workflows/publish-version.yml, .github/workflows/test.yml, .github/workflows/version-bump.yml
Automatic version bumping and releases weren't working. This PR moves the pypi release parts to a new workflow that pushes tags and publishes releases.
The version bump workflow has also changed, so that it now creates a PR. When that is merged, the publishing workflow should trigger.
=> Create a new workflow to publish releases

src/murfey/server/__init__.py
I've found a couple of instances where the database can be committed to without then being closed:
- Tomography preprocessing flushes
- Particle picking registration if an ispyb picker id is not found
The second one of these would explain why we see spikes in database connections shortly after collections start. Once the picker id is found all the connections end up closed.
Closes #362
=> Database commits can occur without then closing

src/murfey/client/contexts/clem.py, src/murfey/server/api/clem.py, src/murfey/server/demo_api.py, src/murfey/util/models.py, src/murfey/workflows/lif_to_stack.py, src/murfey/workflows/tiff_to_stack.py
* Additionally, fixed minor bugs found in code after last minor update.
=> Added URL posts to register CLEM workflow files

src/murfey/client/analyser.py, src/murfey/client/contexts/spa.py, src/murfey/client/contexts/spa_metadata.py, src/murfey/client/contexts/tomo.py
Allows post transfer hooks for the atlas directory through analyser additions.
Calls the superclass hooks in all contexts.
=> Fixes for picking up external post transfer hooks

src/murfey/server/api/auth.py, src/murfey/util/config.py
so it can be used with existing server setup
=> Move auth URL to machine configuration for now

src/murfey/client/contexts/tomo.py
Removes the functions to extract the tilt series and tag from tomography files, and instead uses the existing `_construct_tilt_series_name` method.
All the tests passed, but it's likely this removes back-compatibility with older tomo versions and SerialEM.
Also changes the angle index determination to be match the function in `cryoem-services`
=> Remove calls to get tilt series and tag

src/murfey/client/contexts/tomo.py, src/murfey/client/instance_environment.py, tests/client/test_context.py
This aims to fix the problems we see where late-started tomography sessions don't run alignment on some tomograms.
In that case the tilt series is never marked as completed by the client, so alignment cannot be run. I've removed a lot of unused or redundant code, and simplified the calls for checking tilt series completion. The completion check is now always run when a tilt is added.
=> Removal of redundant tomography context code

src/murfey/client/contexts/tomo.py, src/murfey/server/__init__.py, src/murfey/server/api/__init__.py
Tomography processing currently fails if there are less than three tilts.
From what I can see, this is just due to trying to find the midpoint. If this can't be found I suggest we return the first angle.
Closes #239
=> Support tomography with only a single tilt

pyproject.toml, src/murfey/util/config.py
Allow extra configuration options to be extracted from the Murfey machine configuration and validated against a pydantic model specified as an entry point. This allows external packages to add their configuration to the Murfey config for convenience
=> Make machine configuration extendable

src/murfey/server/__init__.py
`record_failure` decorator was broken. Looks like we can just remove it
=> Remove decorator for recording method call failures

src/murfey/client/analyser.py, src/murfey/client/contexts/clem.py, src/murfey/client/contexts/spa.py, src/murfey/client/contexts/spa_metadata.py, src/murfey/client/contexts/tomo.py, src/murfey/client/multigrid_control.py, src/murfey/client/tui/app.py, src/murfey/client/tui/controller.css, src/murfey/client/tui/screens.py, src/murfey/instrument_server/api.py, src/murfey/server/__init__.py, src/murfey/server/api/__init__.py, src/murfey/server/api/display.py, src/murfey/server/demo_api.py, src/murfey/server/ispyb.py, src/murfey/server/websocket.py, src/murfey/util/__init__.py, src/murfey/util/config.py
ISPyB may not be in use at other facilities. This removes the requirement for a connection to an ISPyB database. The option to manually name visits is provided and data collection IDs etc. are autoincremented within the Murfey database when there is no ISPyB to interact with.
=> Remove the need for an ISPyB instance

src/murfey/client/contexts/clem.py, src/murfey/workflows/clem/process_raw_tiffs.py
* Removed the '--Zxx--Cxx.tif' part of the file name before parsing the file path to generate a job name. Resolves issue #407.
* Replaces '/' with '--' when generating series names to group the TIFF files under while parsing the transferred data.
=> CLEM workflow bug fixes

src/murfey/client/contexts/tomo.py
On the 200keV systems we see errors on `start_data_collection` posts for tomography due to NaN slit widths.
If the slit width is NaN we should just not insert it and allow it to default to None.
=> Don't accept NaN slit widths

src/murfey/client/multigrid_control.py, src/murfey/client/tui/screens.py, src/murfey/instrument_server/api.py, src/murfey/server/api/instrument.py, src/murfey/server/demo_api.py, src/murfey/util/instrument_models.py, src/murfey/util/models.py
Add functionality to check what controllers the instrument server has running to allow reconnections to sessions following instrument server restarts
=> Endpoints to get controller information from instrument server

src/murfey/client/tui/screens.py
This used to tell users to select it for superresolution data but this seems to be incorrect
=> Change incorrect labelling of button for counted mode

src/murfey/client/multigrid_control.py, src/murfey/client/tui/app.py, src/murfey/util/config.py
Currently the server hosting the rsync daemon used for transfer is always assumed to be the same as that hosting the Murfey server. It is possible that these would be two different hosts which would then require two URLs. Here an `rsync_url` configuration option is added. If left at its default value of `""` the Murfey server URL will be used, otherwise the configured value is used.
=> Optional configuration of rsync daemon host

src/murfey/client/multigrid_control.py, src/murfey/client/tui/app.py, src/murfey/server/api/__init__.py
A suggested fix for the problem seen last week where metadata directories were not made after they were input manually.
This would explicitly make the full directory structure whenever an rsyncer is started.
=> Make directories on starting rsyncers

src/murfey/server/__init__.py
A fix for the problem where a user cancelling and restarting a tilt series leads to the number of tilt files exceeding the number in the mdoc.
The tomo context already considers a series to be complete if it has more tilts than in the mdoc, but the motion correction check did not.
=> Register tilt series as completed if they have more tilts than the mdoc

src/murfey/client/contexts/spa.py, src/murfey/client/contexts/spa_metadata.py, src/murfey/server/__init__.py, src/murfey/server/api/__init__.py, src/murfey/server/ispyb.py, src/murfey/util/db.py, src/murfey/util/models.py
This is complicated and almost certainly buggy. The problems arise because we need to allow for grid square and foil hole updates when metadata becomes available.
=> Make ISPyB records for atlas, grid squares and foil holes

src/murfey/server/__init__.py, src/murfey/util/config.py
Supply required credentials via the Murfey security configuration
=> Remove the need for Zocalo configuration file

src/murfey/server/__init__.py
Use the recipes from Murfey configuration rather than hardcoding them. Also, add foil hole ID to preprocessing message during flush.
=> Fixes for SPA flushing

src/murfey/client/contexts/spa_metadata.py
The client needs to read metadata from the original location, not the destination
=> Attempt to fix `EpuSession.dm` parsing

src/murfey/client/multigrid_control.py, src/murfey/client/rsync.py
Allow the avoidance of the creation of a thread inside rsyncer finalisation. This should simplify the rsyncer finalisation for visit completion.
=> RSyncer finalisation restructure

src/murfey/client/contexts/spa.py, src/murfey/client/contexts/spa_metadata.py, src/murfey/server/ispyb.py, src/murfey/util/spa_metadata.py, src/murfey/workflows/spa/flush_spa_preprocess.py
=> Fixes for grid square and foil hole registration

src/murfey/client/contexts/spa_metadata.py, src/murfey/server/__init__.py, src/murfey/server/api/__init__.py, src/murfey/util/spa_metadata.py, src/murfey/workflows/spa/flush_spa_preprocess.py
Also stops the Atlas.dm read which errors
=> Change the name of the flush functions

src/murfey/workflows/spa/flush_spa_preprocess.py
There is a condition we have hit on the flush where movies cannot be inserted as the foil hole is not inserted. 
This will hopefully ensure that flushed movies only have a foil hole if it is present in the murfey database.
=> Ensure foil hole id is in the database before inserting movie

src/murfey/client/analyser.py, src/murfey/client/contexts/spa.py, src/murfey/client/contexts/tomo.py, src/murfey/client/instance_environment.py, src/murfey/client/multigrid_control.py, src/murfey/client/tui/app.py, src/murfey/client/tui/screens.py, src/murfey/server/api/__init__.py, src/murfey/server/demo_api.py, src/murfey/util/config.py, src/murfey/util/models.py
Also removes some environment parameters which appear to never be set.
=> Remove the old SPA context which we no longer use

src/murfey/client/contexts/clem.py, src/murfey/client/contexts/spa.py, src/murfey/client/multigrid_control.py, src/murfey/client/rsync.py, src/murfey/client/tui/app.py, src/murfey/client/tui/screens.py, src/murfey/instrument_server/api.py, src/murfey/server/__init__.py, src/murfey/server/api/__init__.py, src/murfey/server/api/instrument.py, src/murfey/server/api/spa.py, src/murfey/server/demo_api.py
Currently we assume that the rsync module name forms part of the path but this isn't necessarily the case. We should specify the whole rsync module path as the `rsync_basepath` in the configuration and insert the module name directly where we need it (at the point of construction of the `rsync` command).
=> Change how we use the rsync module specified in the machine configuration

src/murfey/client/contexts/tomo.py, src/murfey/server/__init__.py, src/murfey/server/api/__init__.py, src/murfey/util/db.py, src/murfey/util/models.py
Adds frame count finding for tomography, and passes this on to the processing.
Storing the frame count requires a database change, so we may not want to merge this change immediately.
=> Need frame counts for tomography dose weighting

src/murfey/client/contexts/tomo.py, src/murfey/client/instance_environment.py, src/murfey/client/multigrid_control.py, src/murfey/client/tui/app.py
The client still stores a stash of data collection and processing job calls for tomography before the first mdoc is seen.
However, the server already has a preprocess stash for tomography, so the client one is not needed any more.
This removes the client stash, and just sends all requests on to the server.
=> Remove the client-side stashing for tomography

src/murfey/client/contexts/tomo.py, src/murfey/client/multigrid_control.py, src/murfey/client/tui/app.py
Rather than the old method of stashing all the calls to make, this loops over all tilt series and checks if they can be registered.
=> Restore code to register tomo data collections post mdoc

src/murfey/client/tui/app.py, src/murfey/server/api/__init__.py
This should fix the visit complete button
I can't see any posts to this url in multigrid_control, so we may need to add into there for the web UI
=> Update the visit complete button api call to remove the client id

src/murfey/cli/spa_ispyb_messages.py, src/murfey/client/contexts/spa.py, src/murfey/client/contexts/tomo.py, src/murfey/instrument_server/api.py, src/murfey/server/__init__.py, src/murfey/server/api/__init__.py, src/murfey/server/api/instrument.py, src/murfey/util/db.py, src/murfey/util/models.py, src/murfey/workflows/spa/flush_spa_preprocess.py
Restarting the instrument server causes parameters to be lost, and the gain reference is not set correctly in messages from the instrument server.
This save these into a new table, and uses them in preference to values from the client/instrument
=> Save parameters from instrument server and reuse them from the murfey database

src/murfey/server/api/processing_parameters.py, src/murfey/server/demo_api.py, src/murfey/server/main.py
=> Add endpoint to get session processing parameters

src/murfey/instrument_server/api.py
Either order for the rsyncer setup and processing parameters should now be acceptable
=> Allow setup page order to be switched in web UI

src/murfey/server/api/processing_parameters.py
Add post endpoint for setting session processing parameters
=> Fill out session processing parameters API

pyproject.toml
Streamlined and fixed dependencies for `instrument-server` key:
* `uvicorn[standard]` is included as part of `fastapi[standard]`
* `PyYAML` is included as part of `uvicorn[standard]`
* `cryptography` is the one that is failing to install on `MSYS2`, but is not needed on client side.
=> Fixed package dependencies for 'instrument-server' key

src/murfey/instrument_server/api.py, src/murfey/server/api/instrument.py
Including how many files are queued for transfer and whether the rsync thread is alive
=> Add endpoint which can gather extra rsyncer information

pyproject.toml, src/murfey/client/analyser.py, src/murfey/client/multigrid_control.py, src/murfey/client/rsync.py, src/murfey/client/watchdir.py, src/murfey/client/watchdir_multigrid.py, src/murfey/instrument_server/api.py, src/murfey/server/api/instrument.py, src/murfey/util/__init__.py, src/murfey/util/state.py
The multigrid controller should now be able to handle most of the process of cleaning up all associated threads. Thread completion requests are performed by setting flags and not explicitly waiting for `join`s. Callbacks are then used to notify of thread completion. (`RSyncer` threads are slightly more complicated because they have to perform file removal after completing.) 
On completion of all associated threads the multigrid controller will mark itself as dormant. When new multigrid controllers are added dormant controllers are checked for and removed along with the associated Murfey session data. This could also possibly be triggered when the controller marks itself as dormant for a quicker cleanup?
=> Allow visit completion to run more asynchronously

src/murfey/instrument_server/api.py, src/murfey/server/__init__.py, src/murfey/server/ispyb.py
* Added logic to instrument server's 'upload_gain_reference()' function to look for 'rsync_path' key from MachineConfig before settling on using Murfey's URL.
* Added logs to describe parameters passed to functions for more effective debuging.
=> Instrument Server Fixes

src/murfey/instrument_server/api.py, src/murfey/server/api/instrument.py
Allows better control over when watching starts so that early starting (i.e. before processing parameter specification) can be avoided
=> Separate multigrid watcher setup endpoint from watcher start endpoint

src/murfey/server/__init__.py, src/murfey/server/api/__init__.py, src/murfey/server/demo_api.py, src/murfey/util/models.py
Tomography processing did not allow a dose of zero, which happens if the instrument server is reconnected. This ensures that in that case the processing parameters in the `SessionProcessingParameters` table are used.
=> Override the tomography processing parameters with ones from web ui

src/murfey/instrument_server/api.py, src/murfey/server/api/instrument.py
This adds the length and status of any corresponding analyser queue to the information returned about an rsyncer.
I've ended up breaking the one-to-one relation between endpoints in `server/api/instrument.py` and `instrument_server/api.py`, but this seemed the easiest way to combine the rsyncer and analyser information.
=> Add information about the analysers into the rsyncer api calls

src/murfey/server/api/__init__.py
When pressing the delete button on sessions we sometimes get a key error from prometheus
=> Catch KeyError if there is no monitoring switch to remove

src/murfey/client/multigrid_control.py, src/murfey/client/rsync.py, src/murfey/instrument_server/api.py, src/murfey/server/api/instrument.py
i.e. all associated threads stopped but no cleanup actions for the `rsync` processes
=> Allow a controller to be "abandoned"

src/murfey/client/multigrid_control.py, src/murfey/client/rsync.py, src/murfey/instrument_server/api.py, src/murfey/server/api/__init__.py, src/murfey/server/api/instrument.py, src/murfey/util/config.py, src/murfey/util/db.py, src/murfey/util/instrument_models.py
They will maintain a list of files created after this time rather than transfer them. The intention is for this end time to be specified from the front end on session setup.
=> Allow RSync instances to be given an end time

src/murfey/server/api/workflow.py, src/murfey/server/feedback.py, src/murfey/util/config.py, src/murfey/util/processing_params.py
Resolves one of the doppio-live issues, where we assume a raw directory for SPA.
This instead makes it a configurable option, where the `raw` is added to the path if `process_multiple_datasets` is True, so that in cases such as eBIC where we send multiple datasets to one location they are still divided up.
Also makes the path construction consistent between SPA and tomo, which will need checking.
=> Remove the assumption of a raw directory for processed outputs

src/murfey/client/analyser.py
This was in the no-serialem branch, but I'm doing it separately here to get it into the next patch as it seems to be causing active problems
=> Do not record a context for gain files

src/murfey/workflows/tomo/tomo_metadata.py
I think these are the necessary changes for search map locations on atlases.
Something similar will probably be needed for tomogram locations on search maps
=> Apply shifts needed for atlas displays on Talos and Falcon-Krios

src/murfey/client/analyser.py, src/murfey/client/contexts/tomo.py, src/murfey/client/multigrid_control.py, src/murfey/util/dummy_setup.py, tests/client/test_analyser.py
The SerialEM code has never been used, and if we want to support SerialEM in future it would be better to redo it. This removes all code relating to it.
Also improves and tests the determination of the context in the analyser.
There are some potential difficulties with distinguishing data and metadata. The biggest problem is mdoc files which appear with the same name in both folders.
=> Remove serialem code and revise context determination

src/murfey/util/client.py
Failed client posts are not currently working
=> Update failed client post to use url_path_for

src/murfey/client/contexts/atlas.py, src/murfey/client/contexts/clem.py, src/murfey/client/contexts/fib.py, src/murfey/client/contexts/spa.py, src/murfey/client/contexts/spa_metadata.py, src/murfey/client/contexts/tomo.py, src/murfey/client/contexts/tomo_metadata.py, src/murfey/client/multigrid_control.py, src/murfey/client/tui/app.py, src/murfey/client/tui/main.py, src/murfey/client/tui/screens.py, src/murfey/server/api/clem.py, src/murfey/server/api/file_io_instrument.py, src/murfey/server/api/instrument.py, src/murfey/server/api/session_control.py, src/murfey/server/api/session_info.py, src/murfey/server/api/workflow.py, src/murfey/util/client.py, src/murfey/util/route_manifest.yaml, tests/client/tui/test_main.py
This updates the `capture_post/get/delete` calls to take in the router name and function instead of a url. The url is then constructed.
By doing this any failed calls can send the function name on for reuse.
=> Refactor API posts to send more information on failed posts

src/murfey/client/watchdir_multigrid.py
Multigrid tomo metadata is structured with an intermediate layer:
- session directory
-  sample directories (named `Sample*` as with atlas directories)
- tomo metadata
The corresponding fractions directories are then named `{session directory}_{Sample*}`
Here we attempt to deal with this at the earliest possible stage, starting metadata `rsyncers` for the `Sample*` directories and hoping that everything else follows. The determination of the correct fractions directory obviously must also change for this case.
=> Changes to enable transfer and processing of Tomo5 multigrid data

src/murfey/client/destinations.py, src/murfey/client/watchdir_multigrid.py
- Destination should be from sample not d
- Name tomo metadata as `metadata_Supervisor_..._SampleX`
- Match fractions and metadata in the destinations directory
=> Fixes for tomo multigrid destinations

src/murfey/client/rsync.py
Pressing visit complete currently registers files as skipped in some cases. Anything the rsyncer has seen should probably be flushed when doing visit completion.
=> When finalising an rsyncer set the end time to now

src/murfey/client/contexts/tomo.py, src/murfey/server/api/workflow.py
When a tilt series is cancelled on the microscope, an mdoc gets written and we mark the tilt series as complete.
The current behaviour is then that we process the tomogram and do so again for every newly found tilt.
This PR changes the code to remove knowledge of tilt series length when a new tilt is found (i.e. when length exceeds the number in the mdoc). This then means we will not launch processing again until the mdoc is re-written with the correct length.
Should reduce the number of processing times from ntilts+1 to 2.
Will still need some work on the processing side as the processed star files contain duplicated tomograms.
=> Reset tilt series lengths on repeated tilts, to avoid repeat processing
