DiamondLightSource/python-murfey

- .azure-pipelines/azure-pipelines.yml
- .azure-pipelines/ci.yml
- .azure-pipelines/flake8-validation.py
- .azure-pipelines/syntax-validation.py
- requirements_dev.txt
- setup.cfg
- src/murfey/client/client_main_test.py
- src/murfey/server/main_test.py
This is skipping all the tests involving the difficult parts (ISPyB, client/server, ..) right now, but does already include a running database and RabbitMQ server.
Closes #25
> Run tests on Azure

- src/murfey/client/main.py
- src/murfey/server/main.py
- src/murfey/utils/rsync.py
Have the `rsync` process monitor `POST` to the server when a file is transferred
Closes #6 (in principle)
> Add fucntionality to notify the server when a file has been transferred

- README.md
> Add minimal development environment instructions

- src/murfey/client/__init__.py
- src/murfey/client/main.py
- src/murfey/server/main.py
- src/murfey/server/websocket.py
- src/murfey/utils/rsync.py
Include rsync which runs if 'source' and 'destination' command line arguments are provided. As files are transferred, post requests are made and the server broadcasts to connected clients.
> Include rsync functionality in the client run() method and take command line arguments for file transfer directories.

- src/murfey/client/__init__.py
- src/murfey/client/websocket.py
- src/murfey/templates/bootstrap.html
Modify bootstrap instructions to include slightly more detail.
> Bootstrap info

- src/murfey/server/ispyb.py
- src/murfey/server/main.py
and collect functions in a separate file.
This should be useful later when our ISPyB dealings become more complex.
> Move ISPyB components out of main server script

- requirements_dev.txt
- setup.cfg
- src/murfey/client/__init__.py
- src/murfey/client/update.py
- src/murfey/server/ispyb.py
- src/murfey/server/main.py
- src/murfey/util/models.py
by properly serialising/deserialising using pydantic with a shared model in `murfey.util.models`
> Export current visit list to client

- .mypy.ini
- src/murfey/client/analyser.py
- src/murfey/client/rsync.py
- src/murfey/client/tui/app.py
- src/murfey/server/ispyb.py
- src/murfey/server/main.py
- src/murfey/server/websocket.py
Neaten up the start_dc mechanism (but don't actually send atm)
> Start DC tidy up

- src/murfey/client/customlogging.py
- src/murfey/client/tui/app.py
- src/murfey/client/watchdir.py
Replace it with a normal `Widget` with a `Panel` that displays the most recent logs
> Fix memory leak from scroll view logs

- src/murfey/client/analyser.py
- src/murfey/client/context.py
- src/murfey/client/tui/app.py
- src/murfey/client/tui/forms.py
Add colour and ordering to TUI forms to indicate fields that need to be changed and move those fields to the top of the form
> Improve TUI forms

- src/murfey/client/__init__.py
- src/murfey/client/instance_environment.py
- src/murfey/client/tui/app.py
`rsync` to a directory called `processing` inside of the visit directory
> Rsync the gain reference file if one is found

- setup.cfg
- src/murfey/cli/transfer.py
Just wraps `rsync` with a prompt to check that the user wants to remove files from the source
> Add basic transfer command line tool

- src/murfey/client/context.py
- src/murfey/client/tui/app.py
After the processing parameters form is completed check with the user that they wish to continue. This gives users a chance to go back and check the parameters they entered.
> Check with the user that they want to proceed with processing

- src/murfey/client/context.py
- src/murfey/util/models.py
> Remove tilt number from data collection parameters form

- src/murfey/cli/transfer.py
- src/murfey/client/tui/app.py
Properly handle the rsyncing of the contents of a directory, fix user confirmation of removal and a few other fixes
> Improve generic command line transfer tool

- src/murfey/client/tui/app.py
- src/murfey/server/api.py
- src/murfey/server/config.py
- src/murfey/server/gain.py
- src/murfey/util/models.py
Manipulation is performed with IMOD. IMOD executable paths are therefore now included in machine configuration. Also configure required flips via machine configuration (assumes this won't change often).
> Transfer and manipulate gain reference

- src/murfey/server/api.py
The movie_path comes from 'movie' which we already pass on.
> Add timestamp parameter for the Movie table insert

- src/murfey/client/__init__.py
- src/murfey/client/analyser.py
- src/murfey/client/context.py
- src/murfey/client/instance_environment.py
- src/murfey/client/tui/app.py
- src/murfey/server/__init__.py
- src/murfey/server/api.py
- src/murfey/server/demo_api.py
- src/murfey/server/ispyb.py
- src/murfey/util/models.py
> Add ability to trigger an SPA processing pipeline

- src/murfey/client/__init__.py
- src/murfey/client/analyser.py
- src/murfey/client/context.py
- src/murfey/client/instance_environment.py
- src/murfey/client/tui/app.py
- src/murfey/client/tui/screens.py
- src/murfey/client/watchdir_multigrid.py
- src/murfey/util/__init__.py
With multigrid detector data may be written to the top level of the data directory rather than the visit directory which is created by `murfey`. The metadata files will be written in the visit directory rather than alongside the data files in this case
> Various fixes for multigrid

- requirements_dev.txt
- setup.cfg
- src/murfey/client/analyser.py
- src/murfey/client/context.py
- src/murfey/client/instance_environment.py
- src/murfey/client/tui/app.py
- src/murfey/client/tui/controller.css
- src/murfey/client/tui/forms.py
- src/murfey/client/tui/screens.py
- src/murfey/util/models.py
Add dependencies between form fields to allow them to be disabled based on other form values. Also allow a choice of SPA and tomography processing forms when multigrid is selected
> Improve processing parameter forms

- src/murfey/client/context.py
Suggest a tilt offset value equal to the negative of the midpoint of the tilt range. Currently this just uses one value of the tilt offset for the whole data collection
> Determine tilt offset from tilt range

- src/murfey/client/tui/screens.py
When constructing destinations for display in destination selection screen make sure they do not match each other by default
> Fix for multiple destination selection defaults

- src/murfey/client/rsync.py
- src/murfey/client/tui/app.py
If enabled in machine configuration and after user confirmation
> "New visit" button now removes source data

- src/murfey/client/rsync.py
- src/murfey/client/tui/app.py
- src/murfey/client/watchdir_multigrid.py
And collect files in batches for `rsync` to avoid getting stuck
> Improvements for multiple Image-Disc directories from EPU

- src/murfey/client/context.py
- src/murfey/client/tui/screens.py
- src/murfey/server/api.py
- src/murfey/server/gain.py
If the data is collected in super-resolution then use the unbinned gain reference for processing
> Use unbinned gain reference for superres data

- src/murfey/client/analyser.py
- src/murfey/client/context.py
- src/murfey/client/tui/screens.py
- src/murfey/server/api.py
- src/murfey/server/config.py
- src/murfey/server/demo_api.py
- src/murfey/util/eer.py
- src/murfey/util/models.py
Needs to write a file with fractionation details for MotionCor2
> Add EER support for tomography processing 

- src/murfey/server/__init__.py
Fixes for message handling and recover the ISPyB picker ID
> Fix particle diameter selection for SPA processing

- src/murfey/client/tui/app.py
- src/murfey/client/tui/screens.py
- src/murfey/server/config.py
- src/murfey/util/__init__.py
- tests/util/test_set_default_acquisition_output.py
Designed for setting acqusition software output directories based on visit directory. Needs settings to be JSON and the required setting to be accessible through a chained list of keys.
> Add ability to specify settings files to edit

- src/murfey/client/contexts/spa.py
- src/murfey/client/instance_environment.py
- src/murfey/server/__init__.py
- src/murfey/server/api.py
- src/murfey/server/demo_api.py
- src/murfey/util/db.py
Movies are also labelled as motion corrected for SPA workflows once a message is received back from particle picking. This allows the identification of movies to process on recovery
> Register image numbers for movies to aid recovery

- src/murfey/client/tui/controller.css
- src/murfey/client/tui/screens.py
- src/murfey/server/api.py
- src/murfey/server/demo_api.py
- src/murfey/server/prometheus.py
- src/murfey/server/websocket.py
No UI component for controlling monitoring at the moment as testing is needed
> Add prometheus metric and labels needed for monitoring 

- src/murfey/client/tui/screens.py
- src/murfey/server/api.py
- src/murfey/server/config.py
- src/murfey/server/gain.py
- src/murfey/util/models.py
This requires a different transformation to the K3. At the moment the machine configuration only supports doing one or the other
> Perform gain preparation for EER

- src/murfey/client/context.py
- src/murfey/client/contexts/fib.py
- src/murfey/client/contexts/spa.py
- src/murfey/client/contexts/tomo.py
- src/murfey/server/api.py
- src/murfey/server/bootstrap.py
- src/murfey/server/config.py
- src/murfey/server/main.py
This allows API end points defined in other packages to be included. Also allows the addition of methods to `post_transfer` calls in the `Analyser`
> Add plugin system for processing and API components

- src/murfey/client/tui/app.py
- src/murfey/server/__init__.py
- src/murfey/util/db.py
- src/murfey/util/spa_params.py
> Add capability to extend the SPA pipeline to Refinement and calculate B-Factors

- src/murfey/client/contexts/spa.py
- src/murfey/client/contexts/spa_metadata.py
- src/murfey/server/api.py
- src/murfey/server/demo_api.py
This can only be done once the atlas path has been found from `EpuSession.dm`. Closes #237
> Record grid square locations on atlas in Murfey DB

- setup.cfg
- src/murfey/client/contexts/spa.py
- src/murfey/server/api.py
- src/murfey/server/demo_api.py
> Move thumbnail size determination to server

- src/murfey/client/contexts/spa.py
- src/murfey/client/contexts/spa_metadata.py
Need to use the local atlas path when finding grid square positions client-side
> Fix for grid square location reading

- src/murfey/client/tui/controller.css
- src/murfey/client/tui/screens.py
- src/murfey/server/api.py
- src/murfey/server/config.py
- src/murfey/server/demo_api.py
To support correlative workflows. At the moment only copies TIFFs
> Allow limited download of data from upstream visits on other instruments

- src/murfey/client/tui/app.py
Need to add EER fractionation file to stored tomography preprocessing parameters when relevant. Resolves #270
> Resolve issue of not motion correcting first tilt series in EER

- src/murfey/server/__init__.py
- src/murfey/server/config.py
> Run preprocessing flushes in separate threads

- pyproject.toml
- src/murfey/cli/add_user.py
- src/murfey/client/__init__.py
- src/murfey/client/contexts/fib.py
- src/murfey/client/contexts/spa.py
- src/murfey/client/contexts/spa_metadata.py
- src/murfey/client/contexts/tomo.py
- src/murfey/client/tui/app.py
- src/murfey/client/tui/screens.py
- src/murfey/server/api.py
- src/murfey/server/auth/__init__.py
- src/murfey/server/auth/api.py
- src/murfey/server/config.py
- src/murfey/server/demo_api.py
- src/murfey/server/main.py
- src/murfey/util/__init__.py
- src/murfey/util/db.py
- tests/server/api/test_movies.py
- tests/server/test_main.py
Add functionality to generate and use tokens for basic authorisation. Intend to extend
> Add basic JWT setup

- src/murfey/server/api.py
- src/murfey/server/config.py
- src/murfey/server/spa/api.py
Search a configured directory for a crYOLO model before falling back on a configured default
> Allow user provided crYOLO model

- src/murfey/server/__init__.py
- src/murfey/server/config.py
Appropriately rescale if found
> Search for user provided initial model

- src/murfey/server/config.py
- src/murfey/server/murfey_db.py
The machine configuration is getting quite large. Should try and do something about that soon
> Allow `sqlalchemy` pooling to be turned off

- src/murfey/instrument_server/api.py
- src/murfey/util/models.py
Use a datetime object for file timestamps rather than float
> Facilitate better UI for gain reference selection

- src/murfey/client/tui/app.py
- src/murfey/client/tui/screens.py
Need to use instrument name when getting machine configuration
> Fixes for TUI

- src/murfey/server/__init__.py
Changes our bfactor calculation to linear, and turns on the inserts into ispyb using the program id
> Insert b-factor estimates into ispyb

- src/murfey/client/contexts/clem.py
- src/murfey/client/contexts/spa_metadata.py
- src/murfey/client/tui/app.py
- src/murfey/server/api/__init__.py
- src/murfey/util/__init__.py
- tests/client/test_context.py
Most of these changes are cases where the instrument name is needed.
Also fixes issues with the session registration.
> Changes needed to make the old gui work with the recent updates

- src/murfey/server/__init__.py
Extra refinement jobs with an estimated symmetry will be run purely in `cryoem-services` (with a PR for that almost ready).
However, Murfey needs to do some setup by increasing the job counter, and also needs to be able to handle feedback messages from symmetrised refine jobs.
> Allow extra symmetrised refine jobs

- src/murfey/client/multigrid_control.py
This should fix data collection registration for tomography through the web UI
> Match multigrid controller behaviour for tomography to that inside of the TUI app

- src/murfey/client/multigrid_control.py
- src/murfey/server/__init__.py
- src/murfey/workflows/spa/flush_spa_preprocess.py
Three unrelated minor fixes which I've grouped together:
- The instrument server needs the machine config to know the data substrings and record movies to grafana
- The `atlas_update` call has been nacking as there is no return in the statement
- Foil hole ID errored as it was retrieved after the db had been closed
> A few fixes

- src/murfey/client/contexts/spa_metadata.py
Drop leading `/` and add `Images-Disc*` to path. This uses the most recent `Images-Disc` directory which is not ideal but I couldn't think of a better way to get something working quickly
> Try to fix the data collection group tag again

- src/murfey/server/__init__.py
Add ability to inject extra functionality after registering data collection groups via entry points
> Data collection group registration hooks

- src/murfey/server/ispyb.py
Do not bother to make updates if the update is falsey for atlas
> Avoid removing atlas information from database on updates

- src/murfey/util/db.py
Set up relationship between Session and SessionProcessingParameters tables for cascade delete
> Fix session delete endpoint

- .github/workflows/test.yml
> Update ispyb schema version

- src/murfey/server/api/auth.py
Thanks to George for finding this
> Fix auth url post refactor when tokens are used
